name: Docker Image CI

on:
  push:
    branches: ["main", "cli-mode"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag java-a5:$(date +%s) --tag java-a5:latest

      - name: Run the batch script
        working-directory: ./scripts
        run: ./batch.sh
